import 'dart:convert';
import 'package:http/http.dart' as http;
import '../api_keys.dart';

class GeminiService {
  final String _apiKey = ApiKeys.geminiPromptApiKey;
  final String _baseUrl =
      "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";

  Future<String> generateVideoPrompt({
    required String category,
    required String basicText,
    required String background,
    required String characters,
    String? videoTitle,
    int? duration,
  }) async {
    final prompt =
        """
Act as a professional video prompt engineer. Your task is to build a detailed video generation prompt based on the following details:

${videoTitle != null ? '[Video Title]: $videoTitle' : ''}
[Category Style]: $category
[Environment Description]: $background
[Character Description]: $characters
Topic: $basicText
Explanation Focus: $basicText
${duration != null ? '[Duration]: ${duration}s video' : ''}

Video Style:
High quality 3D,
Pixar-style rendering,
smooth camera movement,
soft studio lighting,
4K resolution,
cinematic composition,
professional educational tone.

IMPORTANT: The output must be a single, highly detailed paragraph that combines all these elements into a coherent scene description suitable for advanced AI video generation tools. Keep it concise and under 900 characters.
""";

    try {
      final response = await http.post(
        Uri.parse('$_baseUrl?key=$_apiKey'),
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode({
          "contents": [
            {
              "parts": [
                {"text": prompt},
              ],
            },
          ],
        }),
      );

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);

        // Check if candidates exist and have content
        if (data['candidates'] != null &&
            data['candidates'].isNotEmpty &&
            data['candidates'][0]['content'] != null &&
            data['candidates'][0]['content']['parts'] != null &&
            data['candidates'][0]['content']['parts'].isNotEmpty) {
          String generatedPrompt =
              data['candidates'][0]['content']['parts'][0]['text'];

          // Veo API works best with prompts under 1000 characters, so we enforce 950 to be safe
          if (generatedPrompt.length > 950) {
            print(
              "⚠️ Prompt too long (${generatedPrompt.length} chars), truncating to 950...",
            );
            generatedPrompt = generatedPrompt.substring(0, 950);
          }

          return generatedPrompt;
        } else {
          return "No response generated by the AI.";
        }
      } else {
        // If it fails again, this will print the exact error from Google
        print("API Error: ${response.body}");
        throw Exception(
          'Failed to generate prompt: ${response.statusCode} - ${response.body}',
        );
      }
    } catch (e) {
      throw Exception('Error calling Gemini API: $e');
    }
  }
}
